### ISSUE TITLE
[refactor]캘린더 뷰 수정

### ISSUE THREAD

**Issue by PicturePark1101** [yourweather/yourweather-android#348]
## ISSUE
- 캘린더 뷰 수정

## To-do
- [x] 날씨 선택창 가운데에 뜨게
- [x] 날짜 선택창 클릭 영역 확장
- [x] 상단 아이콘 삭제
