### ISSUE TITLE
[feat]주간,월간 비교분석 알람기능 구현

### ISSUE THREAD

**Issue by hyemyu** [yourweather/yourweather-android#404]
## ISSUE
- 주간,월간 비교분석뷰 알람기능 구현

## To-do
- [x] 주간,월간 비교분석뷰 알람기능 구현
- [x] 마이페이지 알림기능 주석 제거
- [x] 마이페이지 - 알림기능 뷰 연결

- [ ] 푸시알람 클릭 시 주간/월간 비교분석 뷰로 이동
