### ISSUE TITLE
[fix] 캘린더 상세보기 창 수정

### ISSUE THREAD

**Issue by kangyuri1114** [yourweather/yourweather-android#445]
## ISSUE
- 캘린더 상세보기 창 수정

## To-do
- [x] 캘린더 상세보기 창 수정 - 뷰 구조 새롭게 바꿈
- [x] 상세보기 수정창
- [x] 상세보기 추가 입력 창
- [x] 마이페이지 뒤로가기 터치 영역 넓히기

**Comment by kangyuri1114** [comment]
머지됨
