### ISSUE TITLE
[fix] 타임피커 클릭하지 않으면 뷰 접속한 시각으로 메모 작성

### ISSUE THREAD

**Issue by kangyuri1114** [yourweather/yourweather-android#460]
## ISSUE
- 타임피커 클릭하지 않으면 뷰 접속한 시각으로 메모 작성

## To-do
- [x] 타임피커 클릭하지 않으면 뷰 접속한 시각으로 메모 작성
- [x] 타임피커 디폴트 뷰도 현재 시각으로
- [x] 텍스트뷰 밑에 밑줄 추가

**Comment by kangyuri1114** [comment]
머지됨
