### ISSUE TITLE
[refactor] 홈 화면 광고 뷰 랜덤 솔루션 추가

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather-android#482]
## ISSUE
- 홈 화면 광고 뷰 랜덤 솔루션 추가

## To-do
- [x] 팀원 이름 넣어 솔루션 리스트 파일 생성
- [x] 이동버튼 및 이동 관련 로직 주석처리
- [x] 홈 화면 광고 뷰에 랜덤 솔루션 출력 로직 추가
