### ISSUE TITLE
[fix] 바텀네비 클릭 애니메이션 삭제

### ISSUE THREAD

**Issue by yeriinnn** [yourweather/yourweather-android#526]
## ISSUE
- 바텀네비 클릭 애니메이션 삭제

## To-do
- [x] 바텀네비 클릭 애니메이션 삭제
- [x] 필요없는 파일 삭제
- [x] 홈화면-날씨입력 부분 기본 문구 android->tools 변경
